WITH listings AS (
    SELECT * FROM {{ ref('int_listings_enriched') }}
)

SELECT
    listing_id,
    host_id,
    host_name,
    listing_name,
    neighbourhood,
    latitude,
    longitude,
    property_type,
    room_type,
    accommodates,
    bathrooms,
    bedrooms,
    beds,
    amenities,
    price,
    minimum_nights,
    maximum_nights,
    has_availability,
    availability_365,
    number_of_reviews,
    number_of_reviews_ltm,
    first_review_date,
    last_review_date,
    review_scores_rating,
    review_scores_accuracy,
    review_scores_cleanliness,
    review_scores_checkin,
    review_scores_communication,
    review_scores_location,
    review_scores_value,
    instant_bookable,
    reviews_per_month,
    total_reviews,
    avg_calendar_price,
    available_days,
    total_days,
    occupancy_rate_pct,
    price_tier,
    rating_category
FROM listings
